# SQLite version 3.x
#   gem install postgresql
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'postgresql'

common: &common
    adapter: postgresql
    host: localhost
    port: 5432
    username: postgres
    password: sang

development:
    <<: *common
    database: demo_app_development

test:
    <<: *common
    database: demo_app_test

production:
    <<: *common
    database: demo_app_production
